### ISSUE TITLE
Update the 2024 team

### ISSUE THREAD

**Issue by mbemshey** [HackFrostNL/website-2022#31]
President - Madison
Vice President - William
Project Manager - Rahaf (Advisor)
Web Developer - (Redacted)(Advisor)

Sponsorship Lead - Parsa
Sponsorship Team - Ahmed, Erfan

Marketing Lead - Hayley
Marketing Team -

Logistics Lead - Paulina
Logistics Lead In-Training - Emad
Logistics Team - Mahek, Amelie

Operations Lead - Umama
Operations Team - Girish, Mohammad

Advisors (Non-Voting Roles) - Mathew, Kamal
Not Returning - Laith, Mohammed (hamood), Youssef

**Comment by mbemshey** [comment]
Mohammad Arafat Zaman (operations)
https://www.linkedin.com/in/m-arafatzaman
![](https://cdn.discordapp.com/attachments/807635137494777906/1138897021999255632/Screenshot_20230809-153748_Messenger.jpg)

**Comment by mbemshey** [comment]
Hayley Perry (Marketing Lead)
https://www.linkedin.com/in/hayley-perry-a4890a242/

**Comment by Mudkip** [comment]
Solved by #33
